version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=30 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #container_name: watchtower

  course_page:
    image: mat10243x/devops_docker_course
    build: 
      dockerfile: Dockerfile
    ports:
      - 8080:80
